[["/usr/lib/python3/dist-packages/secretstorage/__init__.py",[false,[["Collection",true,2,["Collection","/usr/lib/python3/dist-packages/secretstorage/collection.py",5]],["create_collection",true,2,["create_collection","/usr/lib/python3/dist-packages/secretstorage/collection.py",12]],["get_all_collections",true,2,["get_all_collections","/usr/lib/python3/dist-packages/secretstorage/collection.py",12]],["get_default_collection",true,2,["get_default_collection","/usr/lib/python3/dist-packages/secretstorage/collection.py",12]],["get_any_collection",true,2,["get_any_collection","/usr/lib/python3/dist-packages/secretstorage/collection.py",12]],["get_collection_by_alias",true,2,["get_collection_by_alias","/usr/lib/python3/dist-packages/secretstorage/collection.py",12]],["search_items",true,2,["search_items","/usr/lib/python3/dist-packages/secretstorage/collection.py",12]],["Item",true,2,["Item","/usr/lib/python3/dist-packages/secretstorage/item.py",5]],["SecretStorageException",true,2,["SecretStorageException","/usr/lib/python3/dist-packages/secretstorage/exceptions.py",5]],["SecretServiceNotAvailableException",true,2,["SecretServiceNotAvailableException","/usr/lib/python3/dist-packages/secretstorage/exceptions.py",5]],["LockedException",true,2,["LockedException","/usr/lib/python3/dist-packages/secretstorage/exceptions.py",5]],["ItemNotFoundException",true,2,["ItemNotFoundException","/usr/lib/python3/dist-packages/secretstorage/exceptions.py",5]],["PromptDismissedException",true,2,["PromptDismissedException","/usr/lib/python3/dist-packages/secretstorage/exceptions.py",5]],["__version_tuple__",true,13,null],["__version__",true,13,null],["__all__",true,13,null],["dbus_init",true,12,null],["check_service_availability",true,12,null]]]]]